name: Deploy Firebase Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g firebase-tools

      - run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > "$HOME/firebase-key.json"

      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - run: |
          cd functions
          npm install
          firebase deploy --only functions --project me-time-stories-beta-a
        env:
          FIREBASE_CLI_DEBUG: "true"
