name: Deploy Firebase Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write service account credentials to file
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > "${HOME}/firebase-key.json"

      - name: Check for Firebase credentials file
        run: |
          if [ ! -s "${HOME}/firebase-key.json" ]; then
            echo "Firebase credentials file missing or empty!"
            exit 1
          fi

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-key.json
        run: |
          cp "${HOME}/firebase-key.json" "${GOOGLE_APPLICATION_CREDENTIALS}"
          firebase deploy --only functions --project me-time-stories-beta-a
